### ISSUE TITLE
Block editor readiness 

### ISSUE THREAD

**Issue by bph** [helen/revision-notes#5]
We use the plugin revision notes on some of the WordPress documentation pages. Now that we use block-editor on many of the page, it would be great if this plugin could be modified to work with the block editor. 
See short discussion in the #docs channel: https://wordpress.slack.com/archives/C02RP4WU5/p1585236209042400

**Comment by theMikeD** [comment]
Working on it.

**Comment by theMikeD** [comment]
Very happy to have this reviewed and improved.
